// Generated by https://quicktype.io

export interface Movies {
    id:          number;
    title:       string | undefined;
    releaseDate: string | undefined;
    price:       number | undefined;
    genre:       string | undefined; 
    rating:      string | undefined;
}
