// Generated by https://quicktype.io

export interface Movies {
    id:          number;
    title:       string;
    releaseDate: string;
    price:       number;
    genre:       string;
    rating:      string;
}
