// Generated by https://quicktype.io

export interface PeopleList {
    id:           number;
    firstName:    string;
    lastName:     string;
    emailAddress: string;
    phoneNumber:  string;
}
